name: ossrh

on:
  push:
    tags:
      - jdependency-*

jobs:
  ossrh:
    runs-on: ubuntu-latest
    environment: maven-central
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Version
      uses: tcurdt/action-verify-version-maven@main

    - name: Setup
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Setup Maven Central
      uses: actions/setup-java@v1
      with: # overwrite settings.xml
        java-version: 14
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Env
      run: |
        echo "Deploying to Maven Central as ${{ secrets.OSSRH_USERNAME }}"
        cat ~/.m2/settings.xml | grep -v "<passphrase"

    - name: Publish to Maven Central
      run: mvn -X -B -Prelease --file pom.xml package deploy
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
