name: ossrh

on:
  release:
    types: [ published ]


jobs:
  ossrh:
    runs-on: ubuntu-latest
    environment: maven-central
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Version
      uses: tcurdt/action-verify-version-maven@main

    - name: Setup
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build
      run: mvn -B deploy --file pom.xml

    - name: Setup Maven Central
      uses: actions/setup-java@v1
      with: # overwrite settings.xml
        java-version: 14
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Publish to Maven Central
      run: mvn -Prelease deploy
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
